"""empty message

Revision ID: 40abfa80da99
Revises: 4961359bda
Create Date: 2018-01-02 23:51:18.820214

"""

# revision identifiers, used by Alembic.
revision = '40abfa80da99'
down_revision = '4961359bda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mchedruli',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('maxLevel', sa.Integer(), nullable=False),
    sa.Column('introLevel', sa.Integer(), nullable=False),
    sa.Column('introToLevelMap', sa.String(), nullable=False),
    sa.Column('charStats', sa.String(), nullable=False),
    sa.Column('chapterProgress', sa.String(), nullable=False),
    sa.Column('answersHistory', sa.String(), nullable=False),
    sa.Column('wrongAnswers', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mchedruli')
    ### end Alembic commands ###
