"""empty message

Revision ID: 4961359bda
Revises: None
Create Date: 2018-01-02 23:49:38.931497

"""

# revision identifiers, used by Alembic.
revision = '4961359bda'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
